- name: Configure Docker and Deploy Insurance App
  hosts: all
  become: true
  connection: ssh

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Docker container for insurance-app
      docker_container:
        name: insurance-app
        image: urvi11umesh/insurance-app:latest
        state: started
        restart_policy: always
        published_ports:
          - "8081:8081"

